import { Job, Qualification, Category, Gender, JobStatus, CompetitionLevel } from './types';

const getFutureDate = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

export const STREAMS = [
  "Arts / Humanities",
  "Commerce",
  "Science",
  "Engineering",
  "Medical",
  "Law",
  "Management",
  "Computer Applications",
  "Education",
  "Other",
  "Not Applicable"
];

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    job_name: 'SSC Multi Tasking Staff (MTS)',
    min_age: 18,
    max_age: 25,
    qualification: Qualification.TENTH,
    category: 'All',
    gender: 'All',
    state: 'All India',
    competition_level: CompetitionLevel.HIGH,
    apply_link: 'https://ssc.gov.in',
    official_website: 'https://ssc.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(10),
    required_streams: ['Any'],
    salary_range: '₹18,000 - ₹22,000 (Level 1)',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '2',
    job_name: 'SBI Probationary Officer (PO)',
    min_age: 21,
    max_age: 30,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: 'https://sbi.co.in/careers',
    official_website: 'https://sbi.co.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(25),
    required_streams: ['Any'],
    salary_range: '₹65,000 - ₹75,000/mo',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '3',
    job_name: 'UP Police Constable',
    min_age: 18,
    max_age: 22,
    qualification: Qualification.TWELFTH,
    category: 'All',
    gender: 'All',
    state: 'Uttar Pradesh',
    competition_level: CompetitionLevel.HIGH,
    apply_link: '#',
    official_website: 'http://uppbpb.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(5),
    required_streams: ['Any'],
    salary_range: '₹21,700 - ₹69,100 (Level 3)',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '4',
    job_name: 'RRB NTPC (Undergraduate)',
    min_age: 18,
    max_age: 30,
    qualification: Qualification.TWELFTH,
    category: 'All',
    gender: 'All',
    state: 'All India',
    competition_level: CompetitionLevel.HIGH,
    apply_link: '#',
    official_website: 'https://indianrailways.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(45),
    required_streams: ['Any'],
    salary_range: '₹19,900 - ₹29,200 (Initial Pay)',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '5',
    job_name: 'Bihar Primary Teacher',
    min_age: 21,
    max_age: 37,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'Bihar',
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: '#',
    official_website: 'https://www.bpsc.bih.nic.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(12),
    required_streams: ['Education', 'Any'],
    salary_range: '₹25,000 Basic + DA + HRA',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '6',
    job_name: 'Indian Army Agniveer (Women)',
    min_age: 17,
    max_age: 21,
    qualification: Qualification.TENTH,
    category: 'All',
    gender: Gender.FEMALE,
    state: 'All India',
    competition_level: CompetitionLevel.LOW,
    apply_link: '#',
    official_website: 'https://joinindianarmy.nic.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(8),
    required_streams: ['Any'],
    salary_range: '₹30,000 (1st Year Package)',
    notification_link: '#'
  },
   {
    id: '7',
    job_name: 'Special SC/ST Drive',
    min_age: 21,
    max_age: 40,
    qualification: Qualification.GRADUATE,
    category: Category.SC,
    gender: 'All',
    state: 'Delhi',
    competition_level: CompetitionLevel.LOW,
    apply_link: '#',
    official_website: 'https://dsssb.delhi.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(20),
    required_streams: ['Any'],
    salary_range: '₹44,900 (Level 7)',
    notification_link: '#'
  },
  {
    id: '8',
    job_name: 'Post Graduate Teacher (PGT)',
    min_age: 21,
    max_age: 40,
    qualification: Qualification.POST_GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'Delhi',
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: '#',
    official_website: 'https://edudel.nic.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(30),
    required_streams: ['Education', 'Any'],
    salary_range: '₹47,600 - ₹1,51,100 (Level 8)',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '9',
    job_name: 'SSC Junior Engineer (Civil/Mech)',
    min_age: 18,
    max_age: 32,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    competition_level: CompetitionLevel.HIGH,
    apply_link: '#',
    official_website: 'https://ssc.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(15),
    required_streams: ['Engineering'],
    salary_range: '₹35,400 - ₹1,12,400 (Level 6)',
    notification_link: '#',
    syllabus_link: '#'
  },
  {
    id: '10',
    job_name: 'Bank Specialist Officer (IT)',
    min_age: 20,
    max_age: 30,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: '#',
    official_website: 'https://ibps.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(18),
    required_streams: ['Engineering', 'Computer Applications'],
    salary_range: '₹48,170 - ₹69,810 (Scale I)',
    notification_link: '#',
    syllabus_link: '#'
  }
];

export const STATES = [
  "All India", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", 
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", 
  "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const TRANSLATIONS = {
  en: {
    appTitle: "Govt Job Eligibility Checker",
    heroTitle: "Find Your\nDream Govt Job",
    heroSubtitle: "Check your eligibility for hundreds of government jobs across India. Enter your details and discover opportunities tailored for you.",
    checkEligibilityHeader: "Check Your Government Job Eligibility",
    statActiveJobs: "Active Jobs",
    statQualifications: "Qualifications",
    statOpportunities: "Opportunities",
    statActiveJobsCount: "500+",
    statQualificationsLabel: "All Levels",
    statOpportunitiesLabel: "Pan India",
    savedJobs: "Saved Jobs",
    alerts: "Alerts",
    competition: "Competition",
    low: "Low",
    medium: "Medium",
    high: "Very High",
    whyHigh: "Why High?",
    whyHighDesc: "Applicants/Seat: ~1:180",
    whyHighDesc2: "Popular national-level exam",
    eligibleJobs: "Eligible Jobs Found",
    results: "Results",
    latestJobs: "Latest Govt Jobs",
    yourSaved: "Your Saved Jobs",
    viewAll: "View All Jobs",
    noSaved: "No saved jobs found matching your eligibility.",
    noJobs: "Currently no matching govt jobs found. Please check back later.",
    browseAll: "Browse All Jobs",
    missedDate: "🚀 Missed the last date? Never again!",
    getAlertsDesc: "Get instant alerts for new vacancies, syllabus updates, and deadline reminders.",
    getFreeAlerts: "Get Free Alerts",
    enterDetails: "Enter Your Details",
    checkJobs: "Check Eligible Jobs",
    clearFilters: "Clear Filters",
    age: "Age (Years)",
    qual: "Qualification",
    stream: "Stream / Discipline",
    category: "Category",
    gender: "Gender",
    statePref: "State Preference (Optional)",
    selectQual: "Select Qualification",
    selectStream: "Select Stream",
    selectCat: "Select Category",
    anywhere: "Anywhere in India",
    ageLimit: "Age Limit",
    deadline: "Deadline",
    daysLeft: "Days Left",
    officialNotif: "Official Notification",
    syllabus: "Syllabus",
    applyNow: "Apply Now",
    officialWebsite: "Official Website",
    shareJob: "Share Job",
    spotMistake: "Spot a mistake? Let us know.",
    feedbackHelp: "Your feedback helps thousands of other students.",
    submit: "Submit",
    madeFor: "Made for Aspirants, by Aspirants.",
    placeholder: "E.g. Age limit for UP Police is updated...",
    male: "Male",
    female: "Female",
    checkEligibilityTitle: "Am I Eligible?",
    checkEligibilityBtn: "Check Eligibility",
    eligible: "You are Eligible",
    notEligible: "Not Eligible",
    viewEligibleJobs: "View Eligible Jobs"
  },
  hi: {
    appTitle: "सरकारी नौकरी पात्रता जांच",
    heroTitle: "अपनी सपनों की\nसरकारी नौकरी पाएं",
    heroSubtitle: "भारत भर में सैकड़ों सरकारी नौकरियों के लिए अपनी पात्रता जांचें। अपना विवरण दर्ज करें और अपने लिए उपयुक्त अवसर खोजें।",
    checkEligibilityHeader: "अपनी सरकारी नौकरी पात्रता जांचें",
    statActiveJobs: "सक्रिय नौकरियां",
    statQualifications: "योग्यताएं",
    statOpportunities: "अवसर",
    statActiveJobsCount: "500+",
    statQualificationsLabel: "सभी स्तर",
    statOpportunitiesLabel: "अखिल भारतीय",
    savedJobs: "सहेजी गई",
    alerts: "अलर्ट",
    competition: "प्रतिस्पर्धा",
    low: "कम",
    medium: "मध्यम",
    high: "बहुत अधिक",
    whyHigh: "अधिक क्यों?",
    whyHighDesc: "आवेदक/सीट: ~1:180",
    whyHighDesc2: "लोकप्रिय राष्ट्रीय परीक्षा",
    eligibleJobs: "पात्र नौकरियां मिलीं",
    results: "परिणाम",
    latestJobs: "नवीनतम सरकारी नौकरियां",
    yourSaved: "आपकी सहेजी गई नौकरियां",
    viewAll: "सभी देखें",
    noSaved: "आपकी पात्रता से मेल खाती कोई सहेजी गई नौकरी नहीं मिली।",
    noJobs: "वर्तमान में कोई मेल खाती सरकारी नौकरी नहीं मिली।",
    browseAll: "सभी नौकरियां देखें",
    missedDate: "🚀 क्या अंतिम तिथि निकल गई? अब नहीं!",
    getAlertsDesc: "नई रिक्तियों, पाठ्यक्रम अपडेट और समय सीमा अनुस्मारक के लिए तुरंत अलर्ट प्राप्त करें।",
    getFreeAlerts: "मुफ्त अलर्ट प्राप्त करें",
    enterDetails: "अपना विवरण दर्ज करें",
    checkJobs: "पात्र नौकरियां देखें",
    clearFilters: "फ़िल्टर रीसेट करें",
    age: "आयु (वर्ष)",
    qual: "योग्यता",
    stream: "विषय / स्ट्रीम",
    category: "श्रेणी",
    gender: "लिंग",
    statePref: "राज्य प्राथमिकता (वैकल्फिक)",
    selectQual: "योग्यता चुनें",
    selectStream: "विषय चुनें",
    selectCat: "श्रेणी चुनें",
    anywhere: "पूरे भारत में",
    ageLimit: "आयु सीमा",
    deadline: "अंतिम तिथि",
    daysLeft: "दिन शेष",
    officialNotif: "आधिकारिक अधिसूचना",
    syllabus: "पाठ्यक्रम",
    applyNow: "आवेदन करें",
    officialWebsite: "आधिकारिक वेबसाइट",
    shareJob: "साझा करें",
    spotMistake: "कोई गलती दिखी? हमें बताएं।",
    feedbackHelp: "आपकी प्रतिक्रिया हजारों छात्रों की मदद करती है।",
    submit: "जमा करें",
    madeFor: "छात्रों के लिए, छात्रों द्वारा।",
    placeholder: "जैसे: यूपी पुलिस की आयु सीमा अपडेट हुई है...",
    male: "पुरुष",
    female: "महिला",
    checkEligibilityTitle: "क्या मैं योग्य हूं?",
    checkEligibilityBtn: "पात्रता जांचें",
    eligible: "आप योग्य हैं",
    notEligible: "योग्य नहीं",
    viewEligibleJobs: "योग्य नौकरियां देखें"
  }
};
