
import { Job, Qualification, Category, Gender, JobStatus, CompetitionLevel } from './types';

const getFutureDate = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

export const STREAMS = [
  "Arts / Humanities",
  "Commerce",
  "Science",
  "Engineering",
  "Medical",
  "Law",
  "Management",
  "Computer Applications",
  "Education",
  "Other",
  "Not Applicable"
];

export const MOCK_JOBS: Job[] = [
  // Fixed missing properties in Job 1
  {
    id: '1',
    job_name: 'SSC Multi Tasking Staff (MTS)',
    organization: 'Staff Selection Commission',
    min_age: 18,
    max_age: 25,
    qualification: Qualification.TENTH,
    category: 'All',
    gender: 'All',
    state: 'All India',
    isCentral: true,
    competition_level: CompetitionLevel.HIGH,
    apply_link: 'https://ssc.gov.in',
    official_website: 'https://ssc.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(10),
    required_streams: ['Any'],
    salary_range: '₹18,000 - ₹22,000 (Level 1)',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '100', obc: '100', sc_st: '0' },
    dates: { start: '2024-01-01', end: getFutureDate(10), exam: '2024-05-15' },
    shortDescription: 'SSC Multi Tasking (Non-Technical) Staff, and Havildar (CBIC & CBN) Examination.',
    seo: { metaTitle: 'SSC MTS Recruitment 2024', metaDescription: 'Apply for SSC MTS 2024. Check eligibility, age limit and fees.', slug: 'ssc-mts-2024' }
  },
  // Fixed missing properties in Job 2
  {
    id: '2',
    job_name: 'SBI Probationary Officer (PO)',
    organization: 'State Bank of India',
    min_age: 21,
    max_age: 30,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    isCentral: true,
    competition_level: CompetitionLevel.HIGH,
    apply_link: 'https://sbi.co.in/careers',
    official_website: 'https://sbi.co.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(25),
    required_streams: ['Any'],
    salary_range: '₹65,000 - ₹75,000/mo',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '750', obc: '750', sc_st: '0' },
    dates: { start: '2024-02-01', end: getFutureDate(25), exam: '2024-06-20' },
    shortDescription: 'Recruitment of Probationary Officers in State Bank of India.',
    seo: { metaTitle: 'SBI PO Recruitment 2024', metaDescription: 'SBI PO 2024 Apply Online. Graduation required.', slug: 'sbi-po-2024' }
  },
  // Fixed missing properties in Job 3
  {
    id: '3',
    job_name: 'UP Police Constable',
    organization: 'UPPRPB',
    min_age: 18,
    max_age: 22,
    qualification: Qualification.TWELFTH,
    category: 'All',
    gender: 'All',
    state: 'Uttar Pradesh',
    isCentral: false,
    competition_level: CompetitionLevel.HIGH,
    apply_link: '#',
    official_website: 'http://uppbpb.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(5),
    required_streams: ['Any'],
    salary_range: '₹21,700 - ₹69,100 (Level 3)',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '400', obc: '400', sc_st: '400' },
    dates: { start: '2024-03-01', end: getFutureDate(5), exam: '2024-07-10' },
    shortDescription: 'Direct recruitment for the post of Constable Civil Police.',
    seo: { metaTitle: 'UP Police Constable Vacancy 2024', metaDescription: 'UP Police Constable Recruitment details.', slug: 'up-police-constable-2024' }
  },
  // Fixed missing properties in Job 4
  {
    id: 'ibps-1',
    job_name: 'IBPS Clerk CRP XIV',
    organization: 'Institute of Banking Personnel Selection',
    min_age: 20,
    max_age: 28,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    isCentral: true,
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: 'https://ibps.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(15),
    required_streams: ['Any'],
    salary_range: '₹28,000 - ₹35,000/mo',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '850', obc: '850', sc_st: '175' },
    dates: { start: '2024-04-01', end: getFutureDate(15), exam: '2024-08-25' },
    shortDescription: 'Common Recruitment Process for Recruitment of Clerks in Participating Banks.',
    seo: { metaTitle: 'IBPS Clerk CRP XIV 2024', metaDescription: 'IBPS Clerk Recruitment notification and apply link.', slug: 'ibps-clerk-2024' }
  },
  // Fixed missing properties in Job 5
  {
    id: 'isro-1',
    job_name: 'ISRO Scientist/Engineer (SC)',
    organization: 'Indian Space Research Organisation',
    min_age: 18,
    max_age: 30,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'Karnataka',
    isCentral: true,
    competition_level: CompetitionLevel.LOW,
    apply_link: 'https://isro.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(40),
    required_streams: ['Engineering'],
    salary_range: '₹56,100 (Level 10)',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '250', obc: '250', sc_st: '0' },
    dates: { start: '2024-05-01', end: getFutureDate(40), exam: '2024-09-30' },
    shortDescription: "Recruitment of Scientist/Engineer 'SC' with BE/B.Tech or equivalent degree.",
    seo: { metaTitle: 'ISRO Scientist Recruitment 2024', metaDescription: 'Join ISRO as a Scientist. Engineering graduates apply now.', slug: 'isro-scientist-2024' }
  },
  // Fixed missing properties in Job 6
  {
    id: 'dmrc-1',
    job_name: 'DMRC Executive Trainee',
    organization: 'Delhi Metro Rail Corporation',
    min_age: 21,
    max_age: 28,
    qualification: Qualification.POST_GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'Delhi',
    isCentral: false,
    competition_level: CompetitionLevel.LOW,
    apply_link: 'https://delhimetrorail.com',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(20),
    required_streams: ['Management', 'Engineering'],
    salary_range: '₹50,000 - ₹1,60,000',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '500', obc: '500', sc_st: '250' },
    dates: { start: '2024-06-01', end: getFutureDate(20), exam: '2024-10-12' },
    shortDescription: 'Recruitment for Executive and Non-Executive posts in DMRC.',
    seo: { metaTitle: 'DMRC Executive Trainee 2024', metaDescription: 'Apply for DMRC ET positions. Management and Engineering posts.', slug: 'dmrc-trainee-2024' }
  },
  // Fixed missing properties in Job 7
  {
    id: 'nabard-1',
    job_name: 'NABARD Grade A Manager',
    organization: 'NABARD',
    min_age: 21,
    max_age: 30,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'Maharashtra',
    isCentral: true,
    competition_level: CompetitionLevel.MEDIUM,
    apply_link: 'https://nabard.org',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(30),
    required_streams: ['Commerce', 'Science', 'Arts / Humanities'],
    salary_range: '₹1,00,000+ Gross Pay',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '800', obc: '800', sc_st: '150' },
    dates: { start: '2024-07-01', end: getFutureDate(30), exam: '2024-11-05' },
    shortDescription: "Recruitment of Officers in Grade 'A' (RDBS).",
    seo: { metaTitle: 'NABARD Grade A Officer 2024', metaDescription: 'NABARD Manager recruitment details and application.', slug: 'nabard-grade-a-2024' }
  },
  // Fixed missing properties in Job 8
  {
    id: 'upsc-1',
    job_name: 'UPSC Civil Services (IAS/IPS)',
    organization: 'Union Public Service Commission',
    min_age: 21,
    max_age: 32,
    qualification: Qualification.GRADUATE,
    category: 'All',
    gender: 'All',
    state: 'All India',
    isCentral: true,
    competition_level: CompetitionLevel.HIGH,
    apply_link: 'https://upsc.gov.in',
    status: JobStatus.ACTIVE,
    deadline: getFutureDate(120),
    required_streams: ['Any'],
    salary_range: '₹56,100 - ₹2,50,000',
    notification_link: '#',
    syllabus_link: '#',
    fees: { general: '100', obc: '100', sc_st: '0' },
    dates: { start: '2024-08-01', end: getFutureDate(120), exam: '2025-05-25' },
    shortDescription: 'Civil Services (Preliminary) Examination for IAS/IPS and other services.',
    seo: { metaTitle: 'UPSC Civil Services 2024', metaDescription: 'UPSC IAS/IPS exam notification and eligibility.', slug: 'upsc-cse-2024' }
  }
];

export const STATES = [
  "All India", "Andhra Pradesh", "Arunachal Pradesh", "Assam", "Bihar", "Chhattisgarh", 
  "Delhi", "Goa", "Gujarat", "Haryana", "Himachal Pradesh", "Jharkhand", "Karnataka", 
  "Kerala", "Madhya Pradesh", "Maharashtra", "Manipur", "Meghalaya", "Mizoram", 
  "Nagaland", "Odisha", "Punjab", "Rajasthan", "Sikkim", "Tamil Nadu", "Telangana", 
  "Tripura", "Uttar Pradesh", "Uttarakhand", "West Bengal"
];

export const TRANSLATIONS = {
  en: {
    appTitle: "Govt Job Eligibility Checker",
    heroTitle: "Find Your\nDream Govt Job",
    heroSubtitle: "Serving the nation starts here. Join the backbone of India with a prestigious and secure career.",
    heroCatchyLine: "Desh ki Seva, Aapki Suraksha. Nation building starts with you.",
    checkEligibilityHeader: "Check Your Government Job Eligibility",
    statActiveJobs: "Active Jobs",
    statQualifications: "Qualifications",
    statOpportunities: "Opportunities",
    statActiveJobsCount: "500+",
    statQualificationsLabel: "All Levels",
    statOpportunitiesLabel: "Pan India",
    savedJobs: "Saved Jobs",
    alerts: "Alerts",
    competition: "Competition",
    low: "Low",
    medium: "Medium",
    high: "Very High",
    whyHigh: "Why High?",
    whyHighDesc: "Applicants/Seat: ~1:180",
    whyHighDesc2: "Popular national-level exam",
    eligibleJobs: "Eligible Jobs Found",
    results: "Results",
    latestJobs: "Latest Govt Jobs",
    yourSaved: "Your Saved Jobs",
    viewAll: "View All Jobs",
    noSaved: "No saved jobs found matching your eligibility.",
    noJobs: "Currently no matching govt jobs found. Please check back later.",
    browseAll: "Browse All Jobs",
    missedDate: "🚀 Missed the last date? Never again!",
    getAlertsDesc: "Get instant alerts for new vacancies, syllabus updates, and deadline reminders.",
    getFreeAlerts: "Get Free Alerts",
    enterDetails: "Enter Your Details",
    checkJobs: "Check Eligible Jobs",
    clearFilters: "Clear Filters",
    age: "Age (Years)",
    qual: "Qualification",
    stream: "Stream / Discipline",
    category: "Category",
    gender: "Gender",
    statePref: "State Preference (Optional)",
    selectQual: "Select Qualification",
    selectStream: "Select Stream",
    selectCat: "Select Category",
    anywhere: "Anywhere in India",
    ageLimit: "Age Limit",
    deadline: "Deadline",
    daysLeft: "Days Left",
    officialNotif: "Official Notification",
    syllabus: "Syllabus",
    applyNow: "Apply Now",
    officialWebsite: "Official Website",
    shareJob: "Share Job",
    spotMistake: "Spot a mistake? Let us know.",
    feedbackHelp: "Your feedback helps thousands of other students.",
    submit: "Submit",
    madeFor: "Made for Aspirants, by Aspirants.",
    placeholder: "E.g. Age limit for UP Police is updated...",
    male: "Male",
    female: "Female",
    checkEligibilityTitle: "Am I Eligible?",
    checkEligibilityBtn: "Check Eligibility",
    eligible: "You are Eligible",
    notEligible: "Not Eligible",
    viewEligibleJobs: "View Eligible Jobs",
    quickLatest: "Latest Jobs",
    quickAdmit: "Admit Card",
    quickResult: "Results",
    viewQuick: "View"
  },
  hi: {
    appTitle: "सरकारी नौकरी पात्रता जांच",
    heroTitle: "अपनी सपनों की\nसरकारी नौकरी पाएं",
    heroSubtitle: "देश की सेवा यहाँ से शुरू होती है। एक प्रतिष्ठित और सुरक्षित करियर के साथ भारत की रीढ़ बनें।",
    heroCatchyLine: "देश की सेवा, आपकी सुरक्षा। राष्ट्र निर्माण की शुरुआत आपसे होती है।",
    checkEligibilityHeader: "अपनी सरकारी नौकरी पात्रता जांचें",
    statActiveJobs: "सक्रिय नौकरियां",
    statQualifications: "योग्यताएं",
    statOpportunities: "अवसर",
    statActiveJobsCount: "500+",
    statQualificationsLabel: "सभी स्तर",
    statOpportunitiesLabel: "अखिल भारतीय",
    savedJobs: "सहेजी गई",
    alerts: "अलर्ट",
    competition: "प्रतिस्पर्धा",
    low: "कम",
    medium: "मध्यम",
    high: "बहुत अधिक",
    whyHigh: "अधिक क्यों?",
    whyHighDesc: "आवेदक/सीट: ~1:180",
    whyHighDesc2: "लोकप्रिय राष्ट्रीय परीक्षा",
    eligibleJobs: "पात्र नौकरियां मिलीं",
    results: "परिणाम",
    latestJobs: "नवीनतम सरकारी नौकरियां",
    yourSaved: "आपकी सहेजी गई नौकरियां",
    viewAll: "सभी देखें",
    noSaved: "आपकी पात्रता से मेल खाती कोई सहेजी गई नौकरी नहीं मिली।",
    noJobs: "वर्तमान में कोई मेल खाती सरकारी नौकरी नहीं मिली।",
    browseAll: "सभी नौकरियां देखें",
    missedDate: "🚀 क्या अंतिम तिथि निकल गई? अब नहीं!",
    getAlertsDesc: "नई रिक्तियों, पाठ्यक्रम अपडेट और समय सीमा अनुस्मारक के लिए तुरंत अलर्ट प्राप्त करें।",
    getFreeAlerts: "मुफ्त अलर्ट प्राप्त करें",
    enterDetails: "अपना विवरण दर्ज करें",
    checkJobs: "पात्र नौकरियां देखें",
    clearFilters: "फ़िल्टर रीसेट करें",
    age: "आयु (वर्ष)",
    qual: "योग्यता",
    stream: "विषय / स्ट्रीम",
    category: "श्रेणी",
    gender: "लिंग",
    statePref: "राज्य प्राथमिकता (वैकल्फिक)",
    selectQual: "योग्यता चुनें",
    selectStream: "विषय चुनें",
    selectCat: "श्रेणी चुनें",
    anywhere: "पूरे भारत में",
    ageLimit: "आयु सीमा",
    deadline: "अंतिम तिथि",
    daysLeft: "दिन शेष",
    officialNotif: "आधिकारिक अधिसूचना",
    syllabus: "पाठ्यक्रम",
    applyNow: "आवेदन करें",
    officialWebsite: "आधिकारिक वेबसाइट",
    shareJob: "साझा करें",
    spotMistake: "कोई गलती दिखी? हमें बताएं।",
    feedbackHelp: "आपकी प्रतिक्रिया हजारों छात्रों की मदद करती है।",
    submit: "जमा करें",
    madeFor: "छात्रों के लिए, छात्रों द्वारा।",
    placeholder: "जैसे: यूपी पुलिस की आयु सीमा अपडेट हुई है...",
    male: "पुरुष",
    female: "महिला",
    checkEligibilityTitle: "क्या मैं योग्य हूं?",
    checkEligibilityBtn: "पात्रता जांचें",
    eligible: "आप योग्य हैं",
    notEligible: "योग्य नहीं",
    viewEligibleJobs: "योग्य नौकरियां देखें",
    quickLatest: "नवीनतम नौकरियां",
    quickAdmit: "प्रवेश पत्र",
    quickResult: "परिणाम",
    viewQuick: "देखें"
  }
};
